version: "3"

services:
  chirpstack-network-server:
    container_name: chirpstack_ns
    image: chirpstack/chirpstack-network-server:3
    environment:
      - POSTGRESQL__DSN=postgres://${PSQL_USERNAME}:${PSQL_PASSWORD}@${PSQL_HOST}:@${PSQL_PORT}/${PSQL_DB}?sslmode=${PSQL_SSLMODE}
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=EU868
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://mosquitto:1883
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    depends_on:
      - mosquitto

  chirpstack-application-server:
    container_name: chirpstack_as
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL__DSN=postgres://${PSQL_USERNAME}:${PSQL_PASSWORD}@${PSQL_HOST}/${PSQL_DB}?sslmode=${PSQL_SSLMODE}
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    container_name: chirpstack_gb
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
    depends_on: 
      - mosquitto

  redis:
    container_name: chirpstack_redis
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    container_name: chirpstack_mosquitto
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

  influxdb:
    container_name: chirpstack_influxdb
    image: influxdb:alpine
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
    ports:
      - 8086:8086

volumes:
  redisdata:
