# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://${PSQL_USERNAME:-chirpstack_as}:${PSQL_PASSWORD:-chirpstack_as}@${PSQL_HOST:-postgresql}:${PSQL_PORT:-5432}/${PSQL_DB:-chirpstack_as}?sslmode=${PSQL_SSLMODE:-required}"

[redis]
url="redis://redis:6379"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"

[application_server.api]
public_host="chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecret"
